spring:
 application:
  name: ${APPLICATION_NAME:auth-server}
 jackson:
   serialization:
     WRITE_NULL_MAP_VALUES: false

auth:
 secret:
  ttl: 2678400
 token:
  ttl: 86400
  issuer: "http://ratauth.ru"
 refresh_token:
  ttl: 36000
 code:
  ttl: 86400
 session:
  check_threads: 10
  check_interval: 300
  possible_required_acr_values: ["sms", "ib-username-password", "upupcard",
                              "username", "ad-username-password", "not-client-sms", "corp-username", "employees"]

ru.ratauth.auth.code:
  expires_in_second: 120

ru.ratauth.jwt:
  issuer: "http://ratauth.ru"
  secret: "secret"

ru.ratauth.scope:
  default_scope: "mobile.read"

ru.ratauth.idp.default: "DCA"
ratauth.timeout: 4000
