auth:
 master_secret: "cnlqV2hVQml3aWdrc1RqWXBSaFpma3l5enhNVU1TS1A="
 secret:
  code: "HdC4t2Wpjn/obYj9JHLVwmGzSqQ5SlatYqMF6zuAL0s="
  ttl: 2678400
 token:
  ttl: 86400
  issuer: "http://ratauth.ru"
 refresh_token:
  ttl: 36000
 code:
  ttl: 86400
 session:
  check_threads: 10
  check_interval: 300

openid.properties.discovery:
  issuer: Issuer
  authorization-endpoint: https://server.example.com/connect/authorize
  token_endpoint: https://server.example.com/connect/token
  token-endpoint-auth-signing-alg-values-supported:
    - RSA256
  registration-endpoint: https://server.example.com/connect/register
  user-info-endpoint: https://server.example.com/connect/userinfo
  check-session-iframe: https://server.example.com/connect/check_session
  end-session-endpoint: https://server.example.com/connect/end_session
  afp_endpoint: https://testsense.alfabank.ru/passport/openid-green/register
  subject-types-supported:
    - public
    - pairwise
  responseTypesSupported:
    - code
    - id_token
    - code id_token
    - token id_token
  claims_supported:
    - aud
    - exp
    - iat
    - iss
    - name
    - sub
  scopes_supported:
    - openid
    - profile
  jwks_uri: http://example.com/oauth2/certs

ru.ratauth.idp.default: "STUB"