version: '2'

services:
  run_ratauth:
    image: java:8-alpine
    ports:
      - 5050:5050
    environment:
      SPRING_PROFILES_ACTIVE: local
    volumes:
        - ./server/build/libs:/tmp/app
    command: java -Djava.security.egd=file:/dev/./urandom -jar /tmp/app/server.jar
